#!/usr/bin/env bash

source common_bash.sh

DEBUG=false

# to open the log on at this envionment
function log_view {
    local ip_addr=$(echo "${ANDROID_SERIAL}" | cut -d : -f 1)
    ip_addr_array=($(echo ${ip_addr} | tr '.' ' '))
    local length=${#ip_addr_array[@]}
    local last_index=$(expr ${length} - 1)
    local last_ip=${ip_addr_array[${last_index}]}
    
    local product_name=$(echo "${WORKSPACE_PROJECT}" | tr '[:upper:]' '[:lower:]')
    if [ ! -z ${WORKSPACE_PRODUCT_ALIAS} ]; then
        product_name=$(echo "${WORKSPACE_PRODUCT_ALIAS}" | tr '[:upper:]' '[:lower:]')
    fi

    DATE=$(date "+%y%m%d")
    log_directory="${HOME}/temp"
    log -d "log_directory=${log_directory}"
    log -d "${DATE}_*${last_ip}"
    log_file=$(ls -t ${log_directory}/${DATE}_${product_name}_*${last_ip}*.logcat | head -n1)
    log -d "log_file=${log_file}"
    filter=""

    if [ ! -d "${log_directory}" ]; then
        log -e "${log_directory} is not exist!"
        return 1
    elif [ -f ${log_file} ]; then
        log -d "args = $#"e
        if [ $# -ge 1 ]; then
            for ARG in "$@"; do
                log -d "filter=${filter}"
                if [ ! -z ${filter} ]; then
                    filter="${filter}|"
                fi
                filter="${filter}${ARG}"
            done
            log -d "filter=${filter}"
            log -i "egrep -ai \"${filter}\" ${log_file} | logcat-color"
            egrep -ai "${filter}" ${log_file} | logcat-color
        else
            vi ${log_file}
        fi
    else
        log -e "${log_file} is not exist!"
        return 1
    fi
}

log_view $@
