" for the vundle
"	git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
" include this file
"	echo \"source ${HOME}/workspace/bin/etc/vim/vimrc" > ~/.vimrc
set hlsearch
set nu
set autoindent
set cindent
set laststatus=2
set showmatch
set smartcase
set smarttab
set smartindent
set tabstop=4
set expandtab
set shiftwidth=4 " >> 또는 << 키로 들여 쓰기 할때 스페이스의 갯수. 기본값 8
set ruler
set fileencodings=utf8,euc-kr

set nocompatible              " be iMproved, required
filetype off                  " required
map <F7> <ESC>:set mouse=a<CR>
map <F8> <ESC>:set mouse-=a<CR>

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
	Plugin 'VundleVim/Vundle.vim'
"	Plugin 'vim-airline/vim-airline'
"	Plugin 'vim-airline/vim-airline-themes'
    Plugin 'itchyny/lightline.vim'
    Plugin 'thinca/vim-logcat' "Syntax and trivial utility for logcat(Log for Android).
    Plugin 'AnsiEsc.vim'
    Plugin 'Logcat-syntax-highlighter'
    Plugin 'nathanaelkane/vim-indent-guides'
    Plugin 'sheerun/vim-polyglot'
    Plugin 'rubberduck203/aosp-vim'
call vundle#end()
filetype plugin indent on    " required
